### ISSUE TITLE
migrate执行有漏洞

### ISSUE THREAD

**Issue by sanzhumu** [lbob/xaircraft1.1#3]
migrate 执行的时候没有指定数据库迁移文件的执行顺序，可能导致部分数据库迁移文件无法执行

**Comment by lbob** [comment]
分析readdir的实现源码：

```c
struct dirent *readdir(DIR *dp)
{
	if (!dp || dp->finished)
		return NULL;

	if (dp->offset != 0) {
		if (FindNextFile(dp->handle, &(dp->fileinfo)) == 0) {
			dp->finished = 1;
			return NULL;
		}
	}
	dp->offset++;

	strlcpy(dp->dent.d_name, dp->fileinfo.cFileName, _MAX_FNAME+1);
	dp->dent.d_ino = 1;
	dp->dent.d_reclen = (unsigned short)strlen(dp->dent.d_name);
	dp->dent.d_off = dp->offset;

	return &(dp->dent);
}
```

可知，其中采用 **FindNextFile** 函数实现读取下一个文件，也就是说，其文件名的排序取决于该函数。查询该函数的[文档](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364428%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)得到：

> The order in which the search returns the files, such as alphabetical order, is not guaranteed, and is dependent on the file system. If the data must be sorted, the application must do the ordering after obtaining all the results.

因此，为了确保 **migration** 能够按照预期的顺序进行执行，需要做如下调整：

- 更改 **migration** 文档的名称结构为：m{{timestamp}}(Create|Alter){{tablename}}Table.php
- 读取 **migration** 目录中文件名集合之后，将列表按照文件名的字母顺序进行排序，确保排序是按照预期的。
